import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}

        <Script
          id="affy-pixel"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              var s=document.createElement('script');
              s.async=true;
              s.src='https://cdn.affy.pro/js/pixel.min.js';
              s.setAttribute('data-affy.pro','gObGD0E6X0rv');
              s.setAttribute('data-cookie_duration','60');
              document.head.appendChild(s);
            `,
          }}
        />
      </body>
    </html>
  );
}
