import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* next/script with any strategy pushes to self.__next_s and depends on
            the Next.js runtime — it never emits a real <script> tag in SSR HTML.
            A raw dangerouslySetInnerHTML script is the only guaranteed path. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){if(document.querySelector('script[src*="affy.js"]'))return;var s=document.createElement('script');s.async=true;s.src='https://cdn.affy.pro/affy.js';s.setAttribute('data-affy.pro','gObGD0E6X0rv');s.setAttribute('data-cookie_duration','60');document.head.appendChild(s);})();`,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
